### ISSUE TITLE
fountain-export doesn't overwrite existing PDF file

### ISSUE THREAD

**Issue by bustinbung** [rnkn/fountain-mode#141] opened 2024-02-10 22:03 UTC
Running `fountain-export` doesn't overwrite an existing PDF, even if I answer with `y` to the prompt.

Emacs v29.2
Troff v1.23.0

**Comment by rnkn** [comment] 2024-02-11 02:13
I can't reproduce this. Are you sure you're not seeing an outdated duplicate buffer? e.g. `script.pdf` vs `script.pdf<2>`

**Comment by bustinbung** [comment] 2024-02-12 16:27
I can confirm it's not a duplicate buffer. The file is not modified on disk.

**Comment by rnkn** [comment] 2024-02-13 02:18
This is weird. Okay to debug, try the following:

1. start Emacs with `emacs -Q`
2. `M-x load-file RET path/to/fountain-mode.el`
3. open and export your script

How are you verifying the file has not modified on disk?
What OS are you on?

**Comment by bustinbung** [comment] 2024-02-13 18:31
Using `emacs -Q` seems to have fixed the issue, just unsure why it isn't working with my normal init.
To check file has not been modified, I've been checking the Date Modified metadata tag. Interestingly, when I run `fountain-export`, the file is modified, but the content of the file doesn't change.

I'm running MacOS 14.3. Also using Doom Emacs.

**Comment by rnkn** [comment] 2024-02-14 02:01
Okay that isolates it to something in your config so I’ll close this. Sorry can’t be of more help.

**Closed by rnkn** 2024-02-14 02:01 UTC

**Comment by bustinbung** [comment] 2024-02-14 08:21
Looking into it more, it looks like the `*Fountain troff output*` is created correctly, just something happening between troff generation and PDF generation. Debugging with `edebug` didn't help much either. Completely lost here.

**Comment by rnkn** [comment] 2024-02-15 02:29
It’s a weird one. But if it can’t be reproduced with `emacs -Q` there’s not much I can do sorry.
